[[defintions]]
== Definitions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted as described in <<RFC2119>>.

UTC:: Coordinated Universal Time as maintained since 1988 by the Bureau
International des Poids et Mesures (BIPM) in conjunction with
leap seconds as announced by the International Earth Rotation
and Reference Frames Service <<IERS>>. From 1972 through 1987
UTC was maintained entirely by Bureau International de l'Heure (BIH).
Before 1972 UTC was not generally recognized and
civil time was determined by individual jurisdictions
using different techniques for attempting to follow
Universal Time based on measuring the rotation of the earth.

ABNF:: Augmented Backus-Naur Form, a format used to represent
permissible strings in a protocol or language, as
defined in <<RFC2234>>.

Internet Date/Time Format::
The date/time format defined in section 3 of this document.

Timestamp:: This term is used in this document to refer to an
unambiguous representation of some instant in time.

Z:: A suffix which, when applied to a time, denotes a UTC
offset of 00:00; often spoken "Zulu" from the ICAO
phonetic alphabet representation of the letter "Z".

Time Zone:: A time zone that is a included in the Time Zone Database
(often called `tz` or `zoneinfo`) maintained by IANA.

For more information about time scales, see Appendix E of <<RFC1305>>,
Section 3 of <<ISO8601>>, and the appropriate ITU documents <<ITURTF460-6>>.
